sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tReT3C9JNfWh17ZWhSi
    access-key-secret: WNBaGcvpkw2Me7iarE710LKjgPNePr
    bucket-name: aie1123-web-framework